// <auto-generated />
using System;
using Homework_Adform.DAL.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homework_Adform.DAL.Migrations
{
    [DbContext(typeof(HomeworkDBContext))]
    [Migration("20200913192422_Homework_Adform.DAL.DBContexts.HomeworkDBContextSeed")]
    partial class Homework_AdformDALDBContextsHomeworkDBContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.LabelDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2020, 9, 13, 19, 24, 22, 501, DateTimeKind.Utc).AddTicks(2574),
                            Description = "Label 1"
                        });
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.TodoItemDBModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LabelId")
                        .HasColumnType("bigint");

                    b.Property<long>("ListId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LabelId");

                    b.HasIndex("ListId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2020, 9, 14, 0, 54, 22, 501, DateTimeKind.Local).AddTicks(6928),
                            LabelId = 1L,
                            ListId = 1L,
                            Notes = "Item 1"
                        });
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.TodoListDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LabelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LabelId");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2020, 9, 13, 19, 24, 22, 501, DateTimeKind.Utc).AddTicks(3932),
                            Description = "List 1",
                            LabelId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2020, 9, 13, 19, 24, 22, 501, DateTimeKind.Utc).AddTicks(4996),
                            Description = "List 2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 2L,
                            CreatedDate = new DateTime(2020, 9, 13, 19, 24, 22, 501, DateTimeKind.Utc).AddTicks(5035),
                            Description = "List 3"
                        });
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.UserDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Vinay",
                            LastName = "Tripathi",
                            Password = "123",
                            Username = "vinay"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Ashish",
                            LastName = "Tripathi",
                            Password = "123",
                            Username = "ashish"
                        });
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.LabelDbModel", b =>
                {
                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.UserDbModel", "User")
                        .WithMany("Labels")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.TodoItemDBModel", b =>
                {
                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.UserDbModel", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.LabelDbModel", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.TodoListDbModel", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homework_Adform.CommonLibrary.Models.DBModels.TodoListDbModel", b =>
                {
                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.UserDbModel", "User")
                        .WithMany("Lists")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homework_Adform.CommonLibrary.Models.DBModels.LabelDbModel", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");
                });
#pragma warning restore 612, 618
        }
    }
}
